// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Defines a trigger that fires when the open email meets a specific criteria.
/// When the trigger fires, it executes a specific endpoint, usually
/// in order to create new cards and update the UI.
public struct ContextualTrigger: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The name of the endpoint to call when a message matches the
  /// trigger.
  public var onTriggerFunction: Swift.String = Swift.String()

  /// The type of trigger determines the conditions Gmail uses to show the
  /// add-on.
  public var trigger: OneOf_Trigger? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ContextualTrigger`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ContextualTrigger().with { $0.unconditional = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let unconditional = CodingKeys(stringValue: "unconditional")
    static let onTriggerFunction = CodingKeys(stringValue: "onTriggerFunction")

    static let _knownKeys: Set<Swift.String> = [
      "unconditional",
      "onTriggerFunction",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .onTriggerFunction) {
      self.onTriggerFunction = value
    }

    var trigger: OneOf_Trigger? = nil
    let triggerCheckAndSet = {
      if trigger != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'trigger'"))
      }
      trigger = $0
    }
    if let unconditional = try container.decodeIfPresent(
      UnconditionalTrigger?.self, forKey: .unconditional)
    {
      try triggerCheckAndSet(.unconditional(unconditional))
    }
    self.trigger = trigger
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.onTriggerFunction, forKey: .onTriggerFunction)

    if let choice = self.trigger {
      switch choice {
      case .unconditional(let value):
        try container.encode(value, forKey: .unconditional)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The type of trigger determines the conditions Gmail uses to show the
  /// add-on.
  public enum OneOf_Trigger: Codable, Equatable, Sendable {
    /// UnconditionalTriggers are executed when any mail message is opened.
    indirect case unconditional(UnconditionalTrigger?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.apps.script.type.gmail.ContextualTrigger"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
