// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleAppsScriptType
import GoogleCloudWkt

/// Properties customizing the appearance and execution of a Gmail add-on.
public struct GmailAddOnManifest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Defines an endpoint that will be executed in contexts that don't
  /// match a declared contextual trigger. Any cards generated by this function
  /// will always be available to the user, but may be eclipsed by contextual
  /// content when this add-on declares more targeted triggers.
  ///
  /// If present, this overrides the configuration from
  /// `addOns.common.homepageTrigger`.
  public var homepageTrigger: GoogleAppsScriptType.HomepageExtensionPoint? = nil

  /// Defines the set of conditions that trigger the add-on.
  public var contextualTriggers: [ContextualTrigger] = []

  /// Defines set of [universal
  /// actions](/gmail/add-ons/how-tos/universal-actions) for the add-on. The user
  /// triggers universal actions from the add-on toolbar menu.
  public var universalActions: [UniversalAction] = []

  /// Defines the compose time trigger for a compose time add-on. This is the
  /// trigger that causes an add-on to take action when the user is composing an
  /// email.
  /// All compose time addons are required to have the
  /// gmail.addons.current.action.compose scope even though it might not edit the
  /// draft.
  public var composeTrigger: ComposeTrigger? = nil

  /// The name of an endpoint that verifies that the add-on has
  /// all the required third-party authorizations, by probing the third-party
  /// APIs. If the probe fails, the function should throw an exception to
  /// initiate the authorization flow. This function is called before each
  /// invocation of the add-on, in order to ensure a smooth user experience.
  public var authorizationCheckFunction: Swift.String = Swift.String()

  /// Initialize a new instance of `GmailAddOnManifest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GmailAddOnManifest().with { $0.homepageTrigger = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.apps.script.type.gmail.GmailAddOnManifest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
