// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleAppsScriptType
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Properties customizing the appearance and execution of a Gmail add-on.
public struct GmailAddOnManifest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Defines an endpoint that will be executed in contexts that don't
  /// match a declared contextual trigger. Any cards generated by this function
  /// will always be available to the user, but may be eclipsed by contextual
  /// content when this add-on declares more targeted triggers.
  ///
  /// If present, this overrides the configuration from
  /// `addOns.common.homepageTrigger`.
  public var homepageTrigger: GoogleAppsScriptType.HomepageExtensionPoint? = nil

  /// Defines the set of conditions that trigger the add-on.
  public var contextualTriggers: [ContextualTrigger] = []

  /// Defines set of [universal
  /// actions](/gmail/add-ons/how-tos/universal-actions) for the add-on. The user
  /// triggers universal actions from the add-on toolbar menu.
  public var universalActions: [UniversalAction] = []

  /// Defines the compose time trigger for a compose time add-on. This is the
  /// trigger that causes an add-on to take action when the user is composing an
  /// email.
  /// All compose time addons are required to have the
  /// gmail.addons.current.action.compose scope even though it might not edit the
  /// draft.
  public var composeTrigger: ComposeTrigger? = nil

  /// The name of an endpoint that verifies that the add-on has
  /// all the required third-party authorizations, by probing the third-party
  /// APIs. If the probe fails, the function should throw an exception to
  /// initiate the authorization flow. This function is called before each
  /// invocation of the add-on, in order to ensure a smooth user experience.
  public var authorizationCheckFunction: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `GmailAddOnManifest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GmailAddOnManifest().with { $0.homepageTrigger = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let homepageTrigger = CodingKeys(stringValue: "homepageTrigger")
    static let contextualTriggers = CodingKeys(stringValue: "contextualTriggers")
    static let universalActions = CodingKeys(stringValue: "universalActions")
    static let composeTrigger = CodingKeys(stringValue: "composeTrigger")
    static let authorizationCheckFunction = CodingKeys(stringValue: "authorizationCheckFunction")

    static let _knownKeys: Set<Swift.String> = [
      "homepageTrigger",
      "contextualTriggers",
      "universalActions",
      "composeTrigger",
      "authorizationCheckFunction",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.homepageTrigger = try container.decodeIfPresent(
      GoogleAppsScriptType.HomepageExtensionPoint.self, forKey: .homepageTrigger)
    if let value = try container.decodeIfPresent(
      [ContextualTrigger].self, forKey: .contextualTriggers)
    {
      self.contextualTriggers = value
    }
    if let value = try container.decodeIfPresent([UniversalAction].self, forKey: .universalActions)
    {
      self.universalActions = value
    }
    self.composeTrigger = try container.decodeIfPresent(
      ComposeTrigger.self, forKey: .composeTrigger)
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .authorizationCheckFunction)
    {
      self.authorizationCheckFunction = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.homepageTrigger, forKey: .homepageTrigger)
    try container.encode(self.contextualTriggers, forKey: .contextualTriggers)
    try container.encode(self.universalActions, forKey: .universalActions)
    try container.encodeIfPresent(self.composeTrigger, forKey: .composeTrigger)
    try container.encode(self.authorizationCheckFunction, forKey: .authorizationCheckFunction)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.apps.script.type.gmail.GmailAddOnManifest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
