// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// An action that is always available in the add-on toolbar menu regardless of
/// message context.
public struct UniversalAction: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. User-visible text describing the action, for example, "Add a new
  /// contact."
  public var text: Swift.String = Swift.String()

  /// The type of the action determines the behavior of Gmail when the user
  /// invokes the action.
  public var actionType: OneOf_ActionType? = nil

  /// Initialize a new instance of `UniversalAction`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = UniversalAction().with { $0.text = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case text = "text"
    case openLink = "openLink"
    case runFunction = "runFunction"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.text = try container.decode(Swift.String.self, forKey: .text)

    var actionType: OneOf_ActionType? = nil
    let actionTypeCheckAndSet = {
      if actionType != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'actionType'"))
      }
      actionType = $0
    }
    if let openLink = try container.decodeIfPresent(Swift.String.self, forKey: .openLink) {
      try actionTypeCheckAndSet(.openLink(openLink))
    }
    if let runFunction = try container.decodeIfPresent(Swift.String.self, forKey: .runFunction) {
      try actionTypeCheckAndSet(.runFunction(runFunction))
    }
    self.actionType = actionType
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.text, forKey: .text)

    if let choice = self.actionType {
      switch choice {
      case .openLink(let value):
        try container.encode(value, forKey: .openLink)
      case .runFunction(let value):
        try container.encode(value, forKey: .runFunction)
      }
    }
  }

  /// The type of the action determines the behavior of Gmail when the user
  /// invokes the action.
  public enum OneOf_ActionType: Codable, Equatable, Sendable {
    /// A link that is opened by Gmail when the user triggers the action.
    case openLink(Swift.String)
    /// An endpoint that is called when the user triggers the
    /// action. See the [universal actions
    /// guide](/gmail/add-ons/how-tos/universal-actions) for details.
    case runFunction(Swift.String)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.apps.script.type.gmail.UniversalAction"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
